USE [master];
GO

-- Provision Availability Group container using external orchestration parameters
CREATE AVAILABILITY GROUP [ptag]
WITH (CLUSTER_TYPE = EXTERNAL)
FOR REPLICA ON
N'DB1' WITH (ENDPOINT_URL = N'TCP://192.168.1.1:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = EXTERNAL, SEEDING_MODE = AUTOMATIC),
N'DB2' WITH (ENDPOINT_URL = N'TCP://192.168.1.2:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = EXTERNAL, SEEDING_MODE = AUTOMATIC),
N'DR-DB1' WITH (ENDPOINT_URL = N'TCP://172.30.1.1:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = EXTERNAL, SEEDING_MODE = AUTOMATIC);
GO
