USE [master];
GO

-- Enable secondary connection pooling endpoints definitions metrics
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DB1' WITH (SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL));
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DB2' WITH (SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL));
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DR-DB1' WITH (SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL));
GO

-- Register exact target instance node routing connection address variables strings
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DB1' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://192.168.1.1:1433'));
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DB2' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://192.168.1.2:1433'));
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DR-DB1' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://172.30.1.1:1433'));
GO

-- Apply the explicit prioritization tree maps onto the orchestrator configuration matrices
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DB1' WITH (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST = (N'DB2', N'DB1', N'DR-DB1')));
ALTER AVAILABILITY GROUP [ptag] MODIFY REPLICA ON N'DB2' WITH (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST = (N'DB1', N'DB2', N'DR-DB1')));
GO
